sonar.projectKey=orlandoburli_feature-bacon
sonar.organization=orlandoburli

sonar.projectName=Feature Bacon
sonar.projectVersion=0.1.0

# Sources
sonar.sources=backend/internal,backend/cmd,backend/modules
sonar.tests=backend/internal
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/gen/**,**/vendor/**,**/node_modules/**,**/*.pb.go,**/*_grpc.pb.go

# Go coverage
sonar.go.coverage.reportPaths=backend/coverage.out

# Encoding
sonar.sourceEncoding=UTF-8
