version: "2"
run:
  go: "1.25"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
formatters:
  enable:
    - gofmt
    - goimports
issues:
  exclude-dirs:
    - gen
