sonar.projectKey=orlandoburli_feature-bacon
sonar.organization=orlandoburli

sonar.projectName=Feature Bacon - Backend
sonar.projectVersion=0.1.0

sonar.sources=.
sonar.exclusions=\
  **/gen/**,\
  **/*.pb.go,\
  **/*_grpc.pb.go,\
  **/vendor/**

# Tests
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Go coverage (relative to projectBaseDir)
sonar.go.coverage.reportPaths=coverage.out

# Quality gate
sonar.qualitygate.wait=true

# Encoding
sonar.sourceEncoding=UTF-8
