sonar.projectKey=orlandoburli_feature-bacon-sdk-python
sonar.organization=orlandoburli

sonar.projectName=Feature Bacon - SDK Python
sonar.projectVersion=0.1.0

sonar.sources=src/
sonar.tests=tests/
sonar.exclusions=**/__pycache__/**,*.egg-info/**,dist/**,build/**

sonar.python.coverage.reportPaths=coverage.xml

sonar.qualitygate.wait=true
sonar.sourceEncoding=UTF-8
