sonar.projectKey=orlandoburli_feature-bacon-samples
sonar.organization=orlandoburli

sonar.projectName=Feature Bacon - Samples
sonar.projectVersion=0.1.0

sonar.sources=.
sonar.exclusions=\
  **/node_modules/**,\
  **/target/**,\
  **/__pycache__/**,\
  **/coverage/**,\
  **/dist/**,\
  **/package-lock.json

sonar.go.coverage.reportPaths=05-sdk-go/coverage.out
sonar.javascript.lcov.reportPaths=06-sdk-javascript/coverage/lcov.info
sonar.python.coverage.reportPaths=07-sdk-python/coverage.xml
sonar.python.version=3.10
sonar.coverage.jacoco.xmlReportPaths=08-sdk-java/target/site/jacoco/jacoco.xml

sonar.coverage.exclusions=01-*/**,02-*/**,03-*/**,04-*/**

sonar.qualitygate.wait=false
sonar.sourceEncoding=UTF-8
