sonar.projectKey=orlandoburli_feature-bacon-sdk-java
sonar.organization=orlandoburli

sonar.projectName=Feature Bacon - SDK Java
sonar.projectVersion=0.1.0

sonar.sources=src/main/
sonar.tests=src/test/
sonar.exclusions=target/**

sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.qualitygate.wait=true
sonar.sourceEncoding=UTF-8
