sonar.projectKey=orlandoburli_feature-bacon-sdk-go
sonar.organization=orlandoburli

sonar.projectName=Feature Bacon - SDK Go
sonar.projectVersion=0.1.0

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.qualitygate.wait=true
sonar.sourceEncoding=UTF-8
